name: Deploy to Local Minikube

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl (if needed)
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Verify Minikube is running
        run: |
          minikube status
          kubectl cluster-info

      - name: Create namespace if not exists
        run: |
          kubectl get ns fynbos || kubectl create ns fynbos

      - name: Apply ConfigMap
        run: kubectl apply -f kojo-test/Docker/echo-configmap.yaml

      - name: Apply Deployment
        run: kubectl apply -f kojo-test/Docker/echo-deployment.yaml

      - name: Apply Service
        run: kubectl apply -f kojo-test/Docker/echo-service.yaml

      - name: Apply Allow Port-Forward NetworkPolicy
        run: kubectl apply -f kojo-test/Docker/allow-portforward.yaml || true

      - name: Apply Deny-All NetworkPolicy
        run: kubectl apply -f kojo-test/Docker/deny-all-policy.yaml || true