name: Deploy to EKS on release/* branch

on:
  push:
    branches:
      - 'release/*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<GITHUB_ACTIONS_EKS_ROLE>
          aws-region: <AWS_REGION> # e.g., us-west-2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name <EKS_CLUSTER_NAME> \
            --region <AWS_REGION>

      - name: Create namespace if not exists
        run: |
          kubectl get ns fynbos || kubectl create ns fynbos

      - name: Apply ConfigMap
        run: kubectl apply -f kojo-test/Docker/echo-configmap.yaml

      - name: Apply Deployment
        run: kubectl apply -f kojo-test/Docker/echo-deployment.yaml

      - name: Apply Service
        run: kubectl apply -f kojo-test/Docker/echo-service.yaml

      - name: Apply Allow Port-Forward NetworkPolicy
        run: kubectl apply -f kojo-test/Docker/allow-portforward.yaml || true

      - name: Apply Deny-All NetworkPolicy
        run: kubectl apply -f kojo-test/Docker/deny-all-policy.yaml || true